### PR TITLE
FIX of installation of brew-gems, RubyGems=>3.0.2

### PR DESCRIPTION
**Pull request by JuPlutonic**
IF RubyGems=>3.0.2 only supported parameter is --no-document
Where are some discussions here https://github.com/jordansissel/fpm/pull/1583 and here https://github.com/jordansissel/fpm/issues/1582 (If RubyGems < 2 this PR breaks installation)

### CODE REVIEW

**Comment by JuPlutonic** [comment]
@nicksieger please provide review and Merge/Close.
Thank you.

**Comment by jasonkarns** [comment]
@nicksieger `--no-document` was introduced by RubyGems 2.x. Indeed, the ri/rdoc options were deprecated by 2.x and only just now completely dropped by 3.x

https://blog.rubygems.org/2013/02/24/2.0.0-released.html

**Comment by JuPlutonic** [comment]
Yes, I see what the change is only drops RubyGems 1.x support

**Comment by nicksieger** [comment]
Ah, great, thanks for the clarification. And thanks for the contribution!

**Pull request merged**
